import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, ImagePlus, MapPin, Send, Sparkles } from 'lucide-react';

interface ConsultationViewProps { whatsappNumber: string; }
type FormState = {
  name: string; phone: string; email: string; eventType: string; date: string; time: string; venue: string; guests: string; servings: string; size: string; tiers: string; flavour: string; dietary: string; theme: string; palette: string; budget: string; delivery: string; setup: string; message: string; notes: string;
};

const initialForm: FormState = { name: '', phone: '', email: '', eventType: 'Wedding', date: '', time: '', venue: '', guests: '', servings: '', size: '', tiers: '', flavour: '', dietary: 'Egg / eggless to discuss', theme: '', palette: '', budget: '', delivery: 'Delivery to discuss', setup: 'Venue setup to discuss', message: '', notes: '' };

export default function ConsultationView({ whatsappNumber }: ConsultationViewProps) {
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);
  const [files, setFiles] = useState<string[]>([]);
  const [form, setForm] = useState<FormState>(initialForm);
  const update = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const handleFiles = (event: React.ChangeEvent<HTMLInputElement>) => setFiles(Array.from(event.target.files || []).map((file: File) => file.name));
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    const message = ['Hello Cakeasy, I would like to book a cake consultation.', '', `Name: ${form.name}`, `Phone: ${form.phone}`, `Email: ${form.email || 'Not provided'}`, `Event: ${form.eventType}`, `Date: ${form.date}`, `Preferred delivery time: ${form.time || 'To discuss'}`, `Venue / delivery location: ${form.venue}`, `Guests: ${form.guests || 'To discuss'}`, `Required servings: ${form.servings || 'To discuss'}`, `Preferred cake size: ${form.size || 'To discuss'}`, `Tiers: ${form.tiers || 'To discuss'}`, `Flavour: ${form.flavour || 'To discuss'}`, `Dietary: ${form.dietary}`, `Theme / inspiration: ${form.theme || 'To discuss'}`, `Palette / decor: ${form.palette || 'To discuss'}`, `Budget range: ${form.budget || 'To discuss'}`, `Delivery: ${form.delivery}`, `Venue setup: ${form.setup}`, `Personal message: ${form.message || 'None'}`, `Reference files selected: ${files.length ? files.join(', ') : 'None'}`, `Additional notes: ${form.notes || 'None'}`].join('\n');
    window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
    setSubmitted(true);
  };

  return <div className="space-y-12 pb-20 animate-fadeIn">
    <section className="rounded-[32px] bg-[#251B21] p-8 text-white sm:p-12"><div className="max-w-3xl space-y-5"><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#F7C5D8]"><Sparkles className="h-4 w-4" /> Cakeasy consultation</span><h1 className="font-serif text-4xl sm:text-5xl">Let us design the right cake for the moment.</h1><p className="max-w-2xl text-sm leading-7 text-white/70">A short three-step brief gives Neha the useful context without making you fill out a generic order form.</p></div></section>
    <div className="grid grid-cols-3 gap-2 sm:gap-4">{[['01', 'The occasion'], ['02', 'The design'], ['03', 'The handoff']].map(([number, label], index) => <div key={number} className={`rounded-2xl border p-4 ${step === index + 1 ? 'border-[#D63384] bg-[#FFF7FA]' : 'border-[#EDE3E2] bg-white'}`}><span className={`text-xs font-bold ${step === index + 1 ? 'text-[#D63384]' : 'text-gray-400'}`}>{number}</span><p className="mt-1 text-xs font-bold uppercase tracking-wider text-[#43242F]">{label}</p></div>)}</div>
    <form onSubmit={submit} className="grid grid-cols-1 gap-8 lg:grid-cols-12">
      <div className="rounded-3xl border border-neutral-100 bg-white p-6 shadow-sm sm:p-8 lg:col-span-8">
        {step === 1 && <div className="space-y-7"><SectionTitle eyebrow="Step 1" title="Tell us about the celebration" copy="Start with the practical details. We will use them to guide scale, servings and timing." /><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Your name" value={form.name} onChange={(value) => update('name', value)} required placeholder="Bride, parent, partner or organiser" /><Field label="Phone / WhatsApp" value={form.phone} onChange={(value) => update('phone', value)} required placeholder="Best number to reach you" /><Field label="Email (optional)" type="email" value={form.email} onChange={(value) => update('email', value)} placeholder="For a written quotation" /><SelectField label="What are you celebrating?" value={form.eventType} onChange={(value) => update('eventType', value)} options={['Wedding', 'Engagement', 'Anniversary', 'Child birthday', 'Adult birthday', 'Romantic surprise', 'Corporate celebration', 'Intimate celebration']} /><Field label="Event date" type="date" value={form.date} onChange={(value) => update('date', value)} required /><Field label="Preferred delivery time" value={form.time} onChange={(value) => update('time', value)} placeholder="For example, 4:00 pm" /><Field label="Venue / delivery location" value={form.venue} onChange={(value) => update('venue', value)} required placeholder="Venue, hotel, society or neighbourhood" /><Field label="Approximate guests" value={form.guests} onChange={(value) => update('guests', value)} placeholder="Helps us guide portions" /></div></div>}
        {step === 2 && <div className="space-y-7"><SectionTitle eyebrow="Step 2" title="Shape the design direction" copy="You do not need to know the exact cake yet. Give us the clues and we will help shape the idea." /><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Required servings" value={form.servings} onChange={(value) => update('servings', value)} placeholder="For example, 60 servings" /><Field label="Preferred cake size" value={form.size} onChange={(value) => update('size', value)} placeholder="Bento, 1kg, 2kg, 3 tiers..." /><Field label="Preferred tiers" value={form.tiers} onChange={(value) => update('tiers', value)} placeholder="Leave open if unsure" /><Field label="Flavour / filling" value={form.flavour} onChange={(value) => update('flavour', value)} placeholder="Chocolate, berry, rasmalai..." /></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><SelectField label="Egg / eggless preference" value={form.dietary} onChange={(value) => update('dietary', value)} options={['Egg / eggless to discuss', 'Eggless preferred', 'Egg preferred']} /><Field label="Budget range" value={form.budget} onChange={(value) => update('budget', value)} placeholder="A comfortable planning range" /></div><Field label="Theme, story or reference direction" value={form.theme} onChange={(value) => update('theme', value)} placeholder="Lehenga, football, travel, florals, favourite character, memory..." /><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Colour palette / decor" value={form.palette} onChange={(value) => update('palette', value)} placeholder="Ivory, blush, gold, cobalt..." /><SelectField label="Delivery / setup" value={form.delivery} onChange={(value) => update('delivery', value)} options={['Delivery to discuss', 'Pickup preferred', 'Delivery required']} /></div><SelectField label="Venue setup requirement" value={form.setup} onChange={(value) => update('setup', value)} options={['Venue setup to discuss', 'Setup required', 'No setup needed']} /></div>}
        {step === 3 && <div className="space-y-7"><SectionTitle eyebrow="Step 3" title="Add the details that make it yours" copy="Finish with the personal details and references you would like Neha to see." /><Field label="Personal message / topper text" value={form.message} onChange={(value) => update('message', value)} placeholder="A name, date, inside joke or short message" /><label className="block space-y-2"><span className="text-xs font-bold uppercase tracking-wider text-[#43242F]">Additional notes</span><textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} rows={5} placeholder="Outfits, invitation, flowers, cultural details, allergies or anything else important..." className="w-full resize-none rounded-xl border border-neutral-200 bg-neutral-50 px-3.5 py-3 text-sm text-[#1E1E1E] focus:border-[#D63384] focus:outline-none" /></label><div className="rounded-2xl border border-dashed border-[#F0B7C9] bg-[#FFF7FA] p-5"><label className="flex cursor-pointer items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-[#D63384] shadow-sm"><ImagePlus className="h-5 w-5" /></span><span><span className="block text-sm font-bold text-[#43242F]">Add outfit, invitation, decor or Pinterest references</span><span className="mt-1 block text-xs text-gray-500">Images are selected here, then attached manually in WhatsApp after the brief opens.</span></span><input type="file" accept="image/*" multiple className="sr-only" onChange={handleFiles} /></label>{files.length > 0 && <p className="mt-4 text-xs font-semibold text-[#D63384]">Selected: {files.join(', ')}</p>}</div></div>}
        <div className="mt-8 flex items-center justify-between border-t border-gray-50 pt-6"><button type="button" onClick={() => setStep((current) => Math.max(1, current - 1))} disabled={step === 1} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold uppercase tracking-wider ${step === 1 ? 'text-gray-300' : 'border border-[#EDE3E2] text-[#6D6265]'}`}><ArrowLeft className="h-4 w-4" /> Back</button>{step < 3 ? <button type="button" onClick={() => setStep((current) => current + 1)} className="inline-flex items-center gap-2 rounded-xl bg-[#D63384] px-5 py-3 text-xs font-bold uppercase tracking-wider text-white">Continue <ArrowRight className="h-4 w-4" /></button> : <button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-[#D63384] px-5 py-3.5 text-xs font-bold uppercase tracking-wider text-white hover:bg-[#B02266]">{submitted ? <><Check className="h-4 w-4" /> WhatsApp ready</> : <>Send consultation brief <Send className="h-4 w-4" /></>}</button>}</div>
      </div>
      <aside className="space-y-5 lg:col-span-4"><div className="rounded-3xl bg-[#FFF7FA] p-6"><CalendarDays className="h-6 w-6 text-[#D63384]" /><h2 className="mt-4 font-serif text-2xl font-bold text-[#1E1E1E]">What happens next</h2><div className="mt-5 space-y-4 text-sm leading-6 text-gray-600"><p><b className="text-[#43242F]">1.</b> Your brief opens in WhatsApp for a direct conversation with Cakeasy.</p><p><b className="text-[#43242F]">2.</b> Neha discusses design, servings, flavour, timeline and setup.</p><p><b className="text-[#43242F]">3.</b> You receive a considered quotation before confirming.</p></div></div><div className="rounded-3xl border border-neutral-100 bg-white p-6 text-sm leading-6 text-gray-600"><MapPin className="h-5 w-5 text-[#D63384]" /><p className="mt-3 font-semibold text-[#1E1E1E]">Cakeasy Studio - Greater Noida</p><p className="mt-1">Serving Delhi NCR, with Lucknow roots and a design process built for meaningful celebrations.</p></div></aside>
    </form>
  </div>;
}

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="space-y-2"><span className="text-xs font-bold uppercase tracking-[0.2em] text-[#D63384]">{eyebrow}</span><h2 className="font-serif text-3xl font-bold text-[#251B21]">{title}</h2><p className="text-sm leading-6 text-gray-500">{copy}</p></div>; }
function Field({ label, value, onChange, placeholder, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block space-y-2"><span className="text-xs font-bold uppercase tracking-wider text-[#43242F]">{label}</span><input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-3.5 py-3 text-sm text-[#1E1E1E] focus:border-[#D63384] focus:outline-none" /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="block space-y-2"><span className="text-xs font-bold uppercase tracking-wider text-[#43242F]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-3.5 py-3 text-sm text-[#1E1E1E] focus:border-[#D63384] focus:outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
