import React from 'react';
import { ArrowRight, Check, Heart, Instagram, MessageCircle, Sparkles } from 'lucide-react';
import { MenuItem, AtelierSettings, InstagramPost } from '../types';
import { CAKE_CATEGORY_DATA, PRIMARY_CATEGORIES } from '../data/categoryData';
import ScrollReveal from './ScrollReveal';

interface HomeViewProps {
  products: MenuItem[];
  setCurrentTab: (tab: string) => void;
  setSelectedProduct: (product: MenuItem) => void;
  toggleWishlist: (product: MenuItem) => void;
  wishlistedIds: string[];
  settings: AtelierSettings;
  galleryPosts: InstagramPost[];
}

const designerHighlights = [
  { image: '/gallery/26/img1.jpg', label: 'Kids and character themes', slug: 'designer' },
  { image: '/gallery/15/img1.jpg', label: 'Profession and hobby stories', slug: 'designer' },
  { image: '/gallery/11/img1.jpg', label: 'Floral and fashion-led detail', slug: 'designer' },
  { image: '/gallery/19/img1.jpg', label: 'Story-based celebration cakes', slug: 'designer' },
];

const celebrationJourneys = [
  ['Wedding', 'A multi-tier centrepiece coordinated to the room.', 'wedding'],
  ['Engagement', 'Elegant florals, rings, colours and couple details.', 'engagement'],
  ['Anniversary', 'A memory, date or shared interest shaped in cake.', 'anniversary'],
  ["Child's birthday", 'A designer theme with the reaction in mind.', 'birthday'],
  ['Romantic surprise', 'A personal message and a smaller, thoughtful format.', 'anniversary'],
  ['Intimate celebration', 'Bento cakes and giftable pairings for close circles.', 'bento'],
];

export default function HomeView({ setCurrentTab, settings }: HomeViewProps) {
  const openCategory = (slug: string) => setCurrentTab(`cakes/${slug}`);
  const signatureTiles = PRIMARY_CATEGORIES.map((slug) => ({ ...CAKE_CATEGORY_DATA[slug], slug }));

  return (
    <div className="space-y-24 pb-20 animate-fadeIn">
      <section className="relative overflow-hidden rounded-[38px] bg-[#251B21] text-white">
        <div className="grid grid-cols-1 lg:grid-cols-12 lg:min-h-[620px]">
          <div className="order-2 flex flex-col justify-center space-y-8 p-8 sm:p-12 lg:order-1 lg:col-span-5 lg:p-16">
            <span className="text-xs font-bold uppercase tracking-[0.22em] text-[#F5C178]">Cakeasy by Neha Chaudhary</span>
            <h1 className="font-serif text-5xl font-bold leading-[1.04] sm:text-6xl">Bespoke cakes designed around your celebration.</h1>
            <p className="max-w-xl text-base leading-8 text-white/70">From wedding decor and outfits to birthdays, milestones and personal stories, Cakeasy creates cakes that are designed uniquely for your occasion.</p>
            <div className="flex flex-col gap-3 sm:flex-row"><button onClick={() => setCurrentTab('catalog')} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#D63384] px-6 py-4 text-xs font-bold uppercase tracking-wider hover:bg-[#B02266]">Explore our cakes <ArrowRight className="h-4 w-4" /></button><button onClick={() => setCurrentTab('consultation')} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/25 bg-white/5 px-6 py-4 text-xs font-bold uppercase tracking-wider text-white hover:bg-white/10">Book a consultation</button></div>
            <div className="flex flex-wrap gap-x-6 gap-y-2 text-[10px] font-bold uppercase tracking-wider text-white/45"><span>Lucknow roots</span><span>Greater Noida studio</span><span>Delhi NCR service</span></div>
          </div>
          <div className="order-1 relative min-h-[460px] lg:order-2 lg:col-span-7 lg:min-h-0"><img src="/gallery/1/img1.jpg" alt="Neha Chaudhary, founder and baker behind Cakeasy" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#251B21] via-transparent to-transparent lg:w-2/3" /><div className="absolute bottom-7 left-7 rounded-2xl border border-white/20 bg-black/35 p-4 backdrop-blur-md"><p className="text-[10px] font-bold uppercase tracking-widest text-[#F5C178]">The face behind Cakeasy</p><p className="mt-1 font-serif text-xl">Neha Chaudhary</p><p className="mt-1 text-xs text-white/60">Founder and baker - Lucknow roots, Greater Noida studio</p></div></div>
        </div>
      </section>

      <section className="space-y-10"><div className="max-w-2xl space-y-3"><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">Start with the occasion</span><h2 className="font-serif text-4xl font-bold text-[#251B21]">Choose the kind of celebration you are designing.</h2><p className="text-sm leading-7 text-gray-500">The category tells you what belongs in the brief - scale, mood, design language and the kind of conversation you can have with Cakeasy.</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{signatureTiles.map((tile, index) => <ScrollReveal key={tile.slug} delay={index * 60}><button onClick={() => openCategory(tile.slug)} className="group w-full text-left"><div className="relative aspect-[4/3] overflow-hidden rounded-[26px] bg-[#F7F2EF]"><img src={tile.hero} alt={tile.navLabel} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/5 to-transparent" /><div className="absolute bottom-5 left-5 right-5 text-white"><p className="text-[10px] font-bold uppercase tracking-widest text-[#F5C178]">{tile.eyebrow}</p><h3 className="mt-1 font-serif text-2xl font-bold">{tile.navLabel}</h3><p className="mt-1 text-xs text-white/70">{tile.isSmall ? 'Small, personal and giftable' : tile.styles[0]}</p></div></div></button></ScrollReveal>)}</div></section>

      <section className="border-y border-[#EDE3E2] py-16"><div className="grid grid-cols-1 gap-8 md:grid-cols-4">{[['Designed around your celebration', 'Your palette, decor, outfits, interests or story become part of the design.'], ['Wedding and multi-tier expertise', 'Real multi-tier Cakeasy work for weddings, engagements and anniversaries.'], ['A personal design conversation', 'Neha helps you choose the right scale, flavour, finish and timeline.'], ['Delivery and setup planning', 'We discuss transport, venue access and setup requirements before confirmation.']].map(([title, body]) => <div key={title} className="space-y-3"><Check className="h-5 w-5 text-[#D63384]" /><h3 className="font-serif text-xl font-bold text-[#251B21]">{title}</h3><p className="text-sm leading-6 text-gray-500">{body}</p></div>)}</div></section>

      <section className="grid grid-cols-1 gap-10 rounded-[36px] bg-[#F7F2EF] p-8 sm:p-12 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-5"><img src="/gallery/10/img1.jpg" alt="Cakeasy white floral anniversary cake" className="aspect-[4/5] w-full rounded-[26px] object-cover" /></div><div className="space-y-6 lg:col-span-7 lg:pl-6"><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">For the big yes, the new chapter, the milestone</span><h2 className="font-serif text-4xl font-bold text-[#251B21]">A wedding and celebration cake studio that thinks beyond the sponge.</h2><p className="text-sm leading-7 text-gray-600">Cakeasy can coordinate the cake with a wedding invitation, stage decor, floral arrangement, lehenga, venue palette or a private memory. Tasting, servings, delivery and setup are part of the conversation.</p><div className="flex flex-wrap gap-3"><button onClick={() => openCategory('wedding')} className="inline-flex items-center gap-2 rounded-full bg-[#251B21] px-5 py-3 text-xs font-bold uppercase tracking-wider text-white">Wedding portfolio <ArrowRight className="h-4 w-4" /></button><button onClick={() => setCurrentTab('consultation')} className="inline-flex items-center gap-2 rounded-full border border-[#D8B4B7] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#43242F]">Wedding enquiry</button></div></div></section>

      <section className="space-y-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">Designer cake studio</span><h2 className="mt-2 font-serif text-4xl font-bold text-[#251B21]">The brief can be a theme, a hobby, a person or a feeling.</h2></div><button onClick={() => openCategory('designer')} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#D63384]">Explore designer cakes <ArrowRight className="h-4 w-4" /></button></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{designerHighlights.map((item) => <button key={item.image} onClick={() => openCategory(item.slug)} className="group overflow-hidden rounded-3xl border border-neutral-100 bg-white text-left"><div className="aspect-[4/5] overflow-hidden bg-[#F7F2EF]"><img src={item.image} alt={item.label} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#D63384]">Designer direction</p><p className="mt-1 text-sm font-semibold text-[#43242F]">{item.label}</p></div></button>)}</div></section>

      <section className="space-y-8"><div className="max-w-xl space-y-3"><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">Shop by feeling</span><h2 className="font-serif text-4xl font-bold text-[#251B21]">When you know the moment, not the exact design.</h2></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{celebrationJourneys.map(([title, body, slug]) => <button key={title} onClick={() => openCategory(slug)} className="group flex items-start justify-between gap-5 rounded-2xl border border-[#EDE3E2] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[#D8B4B7]"><span><span className="text-[10px] font-bold uppercase tracking-wider text-[#D63384]">Cakeasy occasion</span><span className="mt-2 block font-serif text-xl font-bold text-[#251B21]">{title}</span><span className="mt-1 block text-xs leading-5 text-gray-500">{body}</span></span><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-[#D63384] transition group-hover:translate-x-1" /></button>)}</div></section>

      <section className="grid grid-cols-1 gap-8 border-t border-[#EDE3E2] pt-16 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-5"><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">Small celebrations, beautifully handled</span><h2 className="mt-3 font-serif text-3xl font-bold text-[#251B21]">Bento cakes, cupcakes, pastries and dessert boxes support the studio.</h2><p className="mt-4 text-sm leading-7 text-gray-500">Start small, gift thoughtfully or build a dessert table. These products are easy to order, but still designed to feel like Cakeasy.</p><button onClick={() => openCategory('bento')} className="mt-6 inline-flex items-center gap-2 rounded-full border border-[#F0B7C9] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#D63384]">See the small-format range <ArrowRight className="h-4 w-4" /></button></div><div className="grid grid-cols-3 gap-3 lg:col-span-7"><button onClick={() => openCategory('bento')} className="group"><img src="/gallery/5/img1.jpg" alt="Small Cakeasy bento cake" className="aspect-square w-full rounded-2xl object-cover transition group-hover:scale-[1.02]" /><span className="mt-2 block text-xs font-bold text-[#43242F]">Bento</span></button><button onClick={() => openCategory('cupcakes')} className="group"><img src="/catalog/product5.jpg" alt="Cakeasy cupcakes" className="aspect-square w-full rounded-2xl object-cover transition group-hover:scale-[1.02]" /><span className="mt-2 block text-xs font-bold text-[#43242F]">Cupcakes</span></button><button onClick={() => openCategory('dessert-boxes')} className="group"><img src="/catalog/product6.jpg" alt="Cakeasy dessert box" className="aspect-square w-full rounded-2xl object-cover transition group-hover:scale-[1.02]" /><span className="mt-2 block text-xs font-bold text-[#43242F]">Dessert boxes</span></button></div></section>

      <section className="rounded-[36px] bg-[#251B21] p-8 text-white sm:p-12"><div className="grid grid-cols-1 gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-7"><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#F5C178]">The Cakeasy custom cake journey</span><h2 className="mt-4 font-serif text-4xl font-bold">A design process that makes the important details feel easy.</h2></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:col-span-5">{['Share your event details', 'Send your inspiration, theme or story', 'Finalise design, flavour, servings and budget', 'Receive the proposal and quotation', 'Confirm with advance payment', 'Cakeasy creates and delivers'].map((step, index) => <div key={step} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3 text-xs font-semibold text-white/80"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#D63384] text-white">{index + 1}</span>{step}</div>)}</div></div></section>

      <section className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-xs font-bold uppercase tracking-[0.22em] text-[#D63384]">Real Cakeasy work</span><h2 className="mt-2 font-serif text-4xl font-bold text-[#251B21]">A curated archive, not a photo dump.</h2></div><a href={settings.instagramUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#D63384]"><Instagram className="h-4 w-4" /> Follow {settings.instagramHandle}</a></div><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><img src="/gallery/8/img1.jpg" alt="Cakeasy floral cake" className="aspect-[3/4] rounded-2xl object-cover" /><img src="/gallery/15/img1.jpg" alt="Cakeasy designer cake" className="aspect-square rounded-2xl object-cover md:mt-8" /><img src="/gallery/23/img1.jpg" alt="Cakeasy anniversary cake" className="aspect-[3/4] rounded-2xl object-cover" /><img src="/gallery/13/img1.jpg" alt="Cakeasy character cake" className="aspect-square rounded-2xl object-cover md:mt-8" /></div><button onClick={() => setCurrentTab('gallery')} className="mx-auto inline-flex items-center gap-2 rounded-full border border-[#F0B7C9] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#D63384]">View all curated work <ArrowRight className="h-4 w-4" /></button></section>

      <section className="rounded-[34px] border border-[#EDE3E2] bg-[#FFF7FA] p-8 text-center sm:p-12"><Heart className="mx-auto h-6 w-6 text-[#D63384]" /><h2 className="mt-4 font-serif text-4xl font-bold text-[#251B21]">Tell us what you are celebrating.</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-gray-600">We will help turn it into a cake that feels truly yours - and make the next step easy.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={() => setCurrentTab('consultation')} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#D63384] px-6 py-3.5 text-xs font-bold uppercase tracking-wider text-white hover:bg-[#B02266]">Start your cake consultation <ArrowRight className="h-4 w-4" /></button><a href="https://wa.me/918810795004" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#F0B7C9] px-6 py-3.5 text-xs font-bold uppercase tracking-wider text-[#D63384]"><MessageCircle className="h-4 w-4" /> Chat on WhatsApp</a></div></section>
    </div>
  );
}
